### PR TITLE
Valid folders and misc

### PR DESCRIPTION
**Pull request by VishVadeva**
- xEdit Cache folder support,
- Delta patch file support (.esu),
- Root builder support,
- LLF ParticleLights support.

### CODE REVIEW

**Comment by Holt59** [comment]
Same as other, this should target `master` and linting will probably fail.

**Comment by Holt59** [comment]
Commenting here but this applies to all PR: `Root` should not be a valid folder, this is specific to root-builder which is not a standard MO2 plugin. People using root-builder should now how to mark a mod as valid by themselves.

**Comment by VishVadeva** [comment]
Okay, do I have to make new PRs targeting master or...?

**Comment by Holt59** [comment]
> Okay, do I have to make new PRs targeting master or...?

I've updated the target branch.

**Pull request closed without merging**
